preprocess :
  input : data/raw/data.csv
  output : data/preprocessed/raw.csv

train:
  data: data/preprocessed/raw.csv
  model: models/model.pkl
  random_state: 42
  n_estimators: 100
  max_depth: 10